services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app/app       # Sync local code with container
    ports:
      - "8000:8000"           # Expose API
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
